# Generated by Django 3.2.7 on 2021-09-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210916_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='members',
            new_name='member',
        ),
    ]
