# Generated by Django 3.2.7 on 2021-09-18 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_members_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('role', models.CharField(blank=True, choices=[('Organizer', 'Organizer'), ('Participant', 'Participant'), ('Presenter', 'Presenter')], default='P', max_length=20)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='groups.user')),
                ('group', models.OneToOneField(blank=True, default='Participant', on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
    ]
