# Generated by Django 3.2.7 on 2021-09-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20210918_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(blank=True, choices=[('Organizer', 'Organizer'), ('Participant', 'Participant'), ('Presenter', 'Presenter')], default='P', max_length=20, null=True),
        ),
    ]
