# Generated by Django 3.2.7 on 2021-09-18 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_groupmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_group', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member_user', serialize=False, to='groups.user'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(blank=True, choices=[('Organizer', 'Organizer'), ('Participant', 'Participant'), ('Presenter', 'Presenter')], default='Participant', max_length=20, null=True),
        ),
    ]
